apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-deployment
spec:
  replicas: 3  # Run 3 pods
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      nodeSelector:
        kubernetes.io/hostname: my-single-node  # Ensure all pods run on the same node
      containers:
        - name: hello-kubernetes
          image: jesemeil/hello-kubernetes:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
