name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract Git SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Application
        run: mvn clean package

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t jesemeil/hello-kubernetes:${{ env.SHA }} .
          docker push jesemeil/hello-kubernetes:${{ env.SHA }}

    outputs:
      image: "jesemeil/hello-kubernetes:${{ env.SHA }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubernetes Cluster (KinD)
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/
          kind create cluster --name hello-k8s

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          kind get kubeconfig --name hello-k8s > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Verify Kubernetes Cluster
        run: kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          sed -i 's|image: jesemeil/hello-kubernetes:.*|image: jesemeil/hello-kubernetes:${{ needs.build.outputs.image }}|' k8s/deployment.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

#name: CI/CD Pipeline
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Build Application
#        run: mvn clean package
#
#      - name: Build and Push Docker Image
#        run: |
#          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#          docker build -t jesemeil/hello-kubernetes:latest .
#          docker push jesemeil/hello-kubernetes:latest
#
#    outputs:
#      image: "jesemeil/hello-kubernetes:latest"
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up Kubernetes Cluster (KinD)
#        run: |
#          curl -Lo kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
#          chmod +x kind
#          sudo mv kind /usr/local/bin/
#          kind create cluster --name hello-k8s
#
#      - name: Set up Kubectl
#        uses: azure/setup-kubectl@v3
#        with:
#          version: "latest"
#
#      - name: Configure Kubeconfig
#        run: |
#          mkdir -p $HOME/.kube
#          kind get kubeconfig --name hello-k8s > $HOME/.kube/config
#          export KUBECONFIG=$HOME/.kube/config
#
#      - name: Verify Kubernetes Cluster
#        run: kubectl cluster-info
#
#      - name: Deploy to Kubernetes
#        run: |
#          kubectl apply -f k8s/deployment.yml
#          kubectl apply -f k8s/service.yml
